apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-service
  namespace: demo-service-prod
  labels:
    app.kubernetes.io/name: demo-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-service
